/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package connectiontest;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Suvonkar Kundu
 */
public class Report1update extends javax.swing.JFrame {

    /**
     * Creates new form Report1update
     */
    
    static int primary;
    public void primarykey(String as)
    {
         primary=Integer.parseInt(as);
    }
    
    
    
    public Report1update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updatetext = new javax.swing.JTextField();
        comboupdate = new javax.swing.JComboBox();
        updatebaton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("select update item");

        comboupdate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select item", "token_day", "status", " " }));

        updatebaton.setText("upadate");
        updatebaton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebatonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updatetext, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(updatebaton)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(updatetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(updatebaton)
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatebatonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebatonActionPerformed
        // TODO add your handling code here:
        String combo=(String) comboupdate.getSelectedItem();
        String text=updatetext.getText();
        Connection connection=new  makeconnection().getDatabaseConnection();
        //connection = Current_stu_connect.getDatabaseConnection();
        try {       
            Statement statement = connection.createStatement();
            statement.executeQuery("update diningtable set "+combo+"="+text+"where voucher_id="+primary);
            System.out.println("update diningtable set "+combo+"="+text+"where voucher_id="+primary);
        } catch (SQLException ex) {
            Logger.getLogger(Report1update.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_updatebatonActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updatebaton;
    private javax.swing.JTextField updatetext;
    // End of variables declaration//GEN-END:variables
}
