/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package connectiontest;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suvonkar Kundu
 */
public class Rrrrrr1 extends javax.swing.JFrame {

    /**
     * Creates new form Rrrrrr1
     */
    DefaultTableModel table_model;
    public Rrrrrr1() {
        initComponents();
        table_model=Table_Test1.getTableModel("select voucher_id, token_day,(case when token_day=30 then 'REGULAR'else 'IRREGULAR'end) as status from DININGTABLE");
             jTable1.setModel(table_model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        updatebaton = new javax.swing.JButton();
        deletebaton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(jTable1);

        updatebaton.setText("update");
        updatebaton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebatonActionPerformed(evt);
            }
        });

        deletebaton.setText("delete");
        deletebaton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebatonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(updatebaton)
                        .addGap(61, 61, 61)
                        .addComponent(deletebaton)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebaton)
                    .addComponent(deletebaton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatebatonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebatonActionPerformed
        // TODO add your handling code here:
        String dataColl = null;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
  	      Boolean chked = Boolean.valueOf(jTable1.getValueAt(i, 0).toString());
	     
              if (chked) {
                   dataColl = jTable1.getValueAt(i, 1).toString();
			//JOptionPane.showMessageDialog(null, dataColl);
                        break;
              }
        }
        Report1update ob=new Report1update();
        ob.primarykey(dataColl);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report1update().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_updatebatonActionPerformed

    private void deletebatonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebatonActionPerformed
        // TODO add your handling code here:
        String dataColl = null;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
  	      Boolean chked = Boolean.valueOf(jTable1.getValueAt(i, 0).toString());
	     
              if (chked) {
                   dataColl = jTable1.getValueAt(i, 1).toString();
			//JOptionPane.showMessageDialog(null, dataColl);
                        break;
              }
        }
        
        Connection connection=new  makeconnection().getDatabaseConnection();
        //connection = Current_stu_connect.getDatabaseConnection();
        try {       
            Statement statement = connection.createStatement();
            statement.executeQuery("delete from studentinfo where voucher_id="+dataColl);
            statement.executeQuery("delete from diningtable where voucher_id="+dataColl);
           System.out.println("delete from diningtable where voucher_id="+dataColl);
        } catch (SQLException ex) {
            Logger.getLogger(Report1update.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_deletebatonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebaton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton updatebaton;
    // End of variables declaration//GEN-END:variables
}
